### ISSUE TITLE
请问作者关于推特爬不完整是怎么回事呢？

### ISSUE THREAD

**Issue by haozhen696** [caolvchong-top/twitter_download#12]
<img width="337" alt="屏幕截图 2023-10-15 223206" src="https://github.com/caolvchong-top/twitter_download/assets/46146893/6831e918-25cd-48c0-bbed-85057be4df40">
<img width="251" alt="屏幕截图 2023-10-15 223216" src="https://github.com/caolvchong-top/twitter_download/assets/46146893/0fc43239-6cd2-4348-ae32-8963fc82bc26">

无法完整爬取整个用户的推特内容，是需要调整哪里的参数吗？麻烦了

**Comment by haozhen696** [comment]
> <img alt="屏幕截图 2023-10-15 223206" width="337" src="https://user-images.githubusercontent.com/46146893/275332441-6831e918-25cd-48c0-bbed-85057be4df40.png"> <img alt="屏幕截图 2023-10-15 223216" width="251" src="https://user-images.githubusercontent.com/46146893/275332444-0fc43239-6cd2-4348-ae32-8963fc82bc26.png">
> 无法完整爬取整个用户的推特内容，是需要调整哪里的参数吗？麻烦了

**Comment by haozhen696** [comment]
> <img alt="屏幕截图 2023-10-15 223206" width="337" src="https://user-images.githubusercontent.com/46146893/275332441-6831e918-25cd-48c0-bbed-85057be4df40.png"> <img alt="屏幕截图 2023-10-15 223216" width="251" src="https://user-images.githubusercontent.com/46146893/275332444-0fc43239-6cd2-4348-ae32-8963fc82bc26.png">
> 无法完整爬取整个用户的推特内容，是需要调整哪里的参数吗？麻烦了

**Comment by caolvchong-top** [comment]
请尽可能描述一下以下信息：
- 目标用户
- 非隐私配置文件截图
- 期望结果 & 实际结果
- 其它有可能影响结果的补充内容

**Comment by haozhen696** [comment]
> 请问题描述以下信息：
> 
> * 目标用户
> * 非隐私配置文件截图
> * 预期结果与实际结果
> * 其他有可能影响结果的补充内容

用户：tadai_mahiro

配置文件：

<img width="245" alt="屏幕截图 2023-10-16 102421" src="https://github.com/caolvchong-top/twitter_download/assets/46146893/1b0fb853-c6be-42ba-9ec6-83152ae1c3f4">

预期爬取整个推特用户的图片但只爬取到2022年7月份的图片就结束了

我把时间也为空测试了，不会影响结果

**Comment by caolvchong-top** [comment]
我这边没能复现你的问题，测试时可以正常下载21-06-01至23-07-01时间区间内的内容。
![Screenshot_2023-10-16-13-57-13-672_com.sonelli.juicessh.jpg](https://github.com/caolvchong-top/twitter_download/assets/57820488/ef1299e0-ee45-44b4-a086-098db1a0dce9)

![IMG_20231016_140022.jpg](https://github.com/caolvchong-top/twitter_download/assets/57820488/1baa85de-ab3a-4db1-a22a-eb8f983281cd)


是否API次数耗尽？或者有其他影响因素？

**Comment by haozhen696** [comment]
谢谢大佬答复，好的，那我重新clone项目，跑一下看看

**Comment by haozhen696** [comment]
> 我这边没能复现你的问题，测试时可以正常下载21-06-01至23-07-01时间区间内的内容。 ![Screenshot_2023-10-16-13-57-13-672_com.sonelli.juicessh.jpg](https://user-images.githubusercontent.com/57820488/275405811-ef1299e0-ee45-44b4-a086-098db1a0dce9.jpg)
> 
> ![IMG_20231016_140022.jpg](https://user-images.githubusercontent.com/57820488/275405826-1baa85de-ab3a-4db1-a22a-eb8f983281cd.jpg)
> 
> 是否API次数耗尽？或者有其他影响因素？

谢谢大佬答复，好的，那我重新clone项目，跑一下看看

**Comment by haozhen696** [comment]
> 找到问题了，对于**媒体**(不包含转推)的选项来说，20-07-07已经到底了
> 
> ![图像](https://user-images.githubusercontent.com/57820488/275596791-56aa416a-c8e9-40d6-9da8-9b7e82ee4033.png)
> 
> 配置文件中**[包含转推]**选项调用的是的话**1**，**[不包含转推]**调用的是**2**
> 
> 看起来**媒体**这个API有时间或者帖子数量限制，具体机制还是狮子
> 
> ![图像](https://user-images.githubusercontent.com/57820488/275597672-9e3e7c49-4465-4856-a7f1-4787795cbcae.png)
> 
> 可以尝试**包含转推**选项，但我估计普通用户一天的 API 调用次数不足以爬到那个时间区域

好的，谢谢大佬答复
