### ISSUE TITLE
运行错误：IndexError: list index out of range

### ISSUE THREAD

**Issue by Sheng-Charles** [caolvchong-top/twitter_download#13]
Exception has occurred: IndexError
list index out of range
  File "I:\huanjingbianliang\123123123\main.py", line 249, in main
    _headers['x-csrf-token'] = re.findall(re_token,_headers['cookie'])[0]
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "I:\huanjingbianliang\123123123\main.py", line 272, in <module>
    main(User_info(i))
IndexError: list index out of range

旧版本一直闪退，刚更新后提示这个，但是cookie是刚刷新出来的，也加了转译。请问这个怎么解决？我发给GPT试着自己解决但实在是看不懂::(

**Comment by Sheng-Charles** [comment]
检查了一下，两个字段都有，格式试过完整cookie，也试过只保留 auth_token 和 ct0 ,都是那个提示
![image](https://github.com/caolvchong-top/twitter_download/assets/58870851/a2657aab-2c5f-4ce5-b616-15bca6e0658e)
![image](https://github.com/caolvchong-top/twitter_download/assets/58870851/38a64069-08d2-4733-9ab5-8d9db2d6c4ef)

**Comment by caolvchong-top** [comment]
看一下ct0的末尾有加冒号吗？
ct0=xxxxxxxxxx;

**Comment by Sheng-Charles** [comment]
牛比！可以了！！谢谢谢谢
