### ISSUE TITLE
获取信息失败

### ISSUE THREAD

**Issue by matcha6666** [caolvchong-top/twitter_download#14]
获取信息失败
{"data":{}}
共耗时:1.6001014709472656秒
共调用1次API
共下载0份图片/视频

**Comment by caolvchong-top** [comment]
请贴一下非隐私配置文件的截图，和程序输出的完整截图

**Comment by matcha6666** [comment]
![Uploading 屏幕截图 2023-11-01 234741.png…]()

**Comment by matcha6666** [comment]
![Uploading 屏幕截图 2023-11-01 234833.png…]()

**Comment by matcha6666** [comment]
![屏幕截图 2023-11-01 234741](https://github.com/caolvchong-top/twitter_download/assets/143941342/4938aed8-9665-4d03-89c8-ebfc92483d87)

**Comment by matcha6666** [comment]
![屏幕截图 2023-11-01 234833](https://github.com/caolvchong-top/twitter_download/assets/143941342/49b0c331-4d90-4efa-8a9c-c8f93e270bb5)

**Comment by caolvchong-top** [comment]
> ![屏幕截图 2023-11-01 234741](https://github.com/caolvchong-top/twitter_download/assets/143941342/4938aed8-9665-4d03-89c8-ebfc92483d87)
> 

用户id的@符号不需要

**Comment by matcha6666** [comment]
确实可以了，哈哈，怪我没仔细看清楚
