### ISSUE TITLE
关于限制指定人回复的推文无法成功下载

### ISSUE THREAD

**Issue by Chankit8** [caolvchong-top/twitter_download#15]
你好，我发现有些账号无法下载成功，有个共性是推文0评论（限制了被任何人评论），这种是可以处理的吗？非私人账号

**Comment by caolvchong-top** [comment]
请尽可能提供一下以下信息：
- 目标用户
- 非隐私配置文件截图
- 期望结果 & 实际结果
- 其它有可能影响结果的补充内容

**Comment by Chankit8** [comment]
> 请尽可能提供一下以下信息：
> 
> * 目标用户
> * 非隐私配置文件截图
> * 期望结果 & 实际结果
> * 其它有可能影响结果的补充内容

目标用户：nem_monta
配置截图：
<img width="782" alt="Snipaste_2023-11-18_21-19-55" src="https://github.com/caolvchong-top/twitter_download/assets/35122233/27964d60-083a-4689-81dc-42abf7697ec7">
期望结果：在指定的2023-11-01开始应该有17条推文
实际结果：下载0条
<img width="354" alt="Snipaste_2023-11-18_21-20-12" src="https://github.com/caolvchong-top/twitter_download/assets/35122233/46db2051-2dbd-45c7-af41-28087be3cc59">
辛苦大佬看下

**Comment by caolvchong-top** [comment]
已修复

**Comment by Chankit8** [comment]
> 已修复

请问具体是什么原因呢

**Comment by caolvchong-top** [comment]
这类账号的返回包里相较于正常账号多了一层包装，我先前没遇到过，所以没适配  

正常账号：
-- 
![644)EAF$CE04PDB1$NJ707T](https://github.com/caolvchong-top/twitter_download/assets/57820488/8f2245cc-b37f-4430-9949-d3ed4fdea3e6)

限制回复账号：
-- 
![NJ}J V7W8LE ( ET_{67B%A](https://github.com/caolvchong-top/twitter_download/assets/57820488/c98a8b4a-afa9-4377-8b67-5e7098fab3d7)


程序已更新，运行新版即可
