### ISSUE TITLE
下载不成功

### ISSUE THREAD

**Issue by yellow1024** [caolvchong-top/twitter_download#17]
总推数(含转推):51
        含图片/视频/音频推数(不含转推):21
        <==================>
        开始爬取...
        
已下载图片/视频:0
已下载图片/视频:0
xxxxx下载完成

之前用的好好的，突然就下载不了了

**Comment by caolvchong-top** [comment]
twitter的接口变了，正在改，这两天更新

**Comment by niuyuxuan** [comment]
> twitter的接口变了，正在改，这两天更新
是请求接口变了吗？twitter里面显示的是You have reached the limit for seeing posts today. Subscribe to see more posts every day.
我这边报这个信息
获取信息失败
{"errors":[{"message":"Could not authenticate you","code":32}]}
不知道跟接口有没有关系？

**Comment by caolvchong-top** [comment]
已更新

**Comment by caolvchong-top** [comment]
> > twitter的接口变了，正在改，这两天更新
> > 是请求接口变了吗？twitter里面显示的是You have reached the limit for seeing posts today. Subscribe to see more posts every day.
> > 我这边报这个信息
> > 获取信息失败
> > {"errors":[{"message":"Could not authenticate you","code":32}]}
> > 不知道跟接口有没有关系？

这个像是 日访问次数 超限制，每个账号每天只能调用一定次数api(查看推文)，超了就只能等一天或是换账号

**Comment by yellow1024** [comment]
新版本有新bug，会不断重复下载

**Comment by caolvchong-top** [comment]
> 新版本有新bug，会不断重复下载

目标用户和运行截图看一下
