### ISSUE TITLE
重复下载问题

### ISSUE THREAD

**Issue by lixinj** [caolvchong-top/twitter_download#18]
2023.12.12版本，同一推文会重复下载多次

顺便，作者大大能帮忙把推文网页码（status/1717859159146951031）就是这串数字放进文件名里面吗，呜呜呜我想通过文件找推文。

作者大大牛逼！！！

**Comment by caolvchong-top** [comment]
已修复

关于通过文件找推文，可以参见文件夹内同步生成的csv文件 

第四列为推文地址，第七列为文件名，一一对应。因文件名格式固定所以不方便修改。 

如图： 
![20231214212550](https://github.com/caolvchong-top/twitter_download/assets/57820488/290cac63-0c67-494a-92c7-c5c9b445204a)
