### ISSUE TITLE
感谢分享，不懂python，瞎搞搞也跑起来了，如果要取文字，需要改main里的哪处

### ISSUE THREAD

**Issue by xiluo** [caolvchong-top/twitter_download#20]

**Comment by caolvchong-top** [comment]
什么文字，可以具体描述一下需求吗

**Comment by xiluo** [comment]
就是纯文字的动态，把文字也保存下来

**Comment by caolvchong-top** [comment]
这个项目目前是单为保存媒体数据设计的，纯文本推文的处理逻辑和这个其实不太一样 

后面有时间的话会重构代码，顺带实现这个功能 

// 但有一个问题，目前twitter限制普通账号一天可调用500次API，爬取所有推文会导致配额迅速流失，一般来讲不足以爬取一些经常发文的用户。

**Comment by Stevenjpc** [comment]
![屏幕截图 2024-04-03 221515](https://github.com/caolvchong-top/twitter_download/assets/75826142/1034919c-1c1e-4036-9c86-54636ba30ec1)
修改了下，可以用自己的喜欢的格式存了

**Comment by caolvchong-top** [comment]
已更新
