### ISSUE TITLE
好难搞，还是没打开

### ISSUE THREAD

**Issue by gewuagewua** [caolvchong-top/twitter_download#22]
作者有空搞个一键傻瓜式的吗

**Comment by caolvchong-top** [comment]
你可以把遇到的问题描述一下，截个图，我看看能不能解决 

一键式比较麻烦，因为最终还得手动获取cookie、修改配置文件

**Comment by gewuagewua** [comment]
> 你可以把遇到的问题描述一下，截个图，我看看能不能解决
> 
> 一键式比较麻烦，因为最终还得手动获取cookie、修改配置文件

你看看我这是咋回事啊，感谢大佬
<img src="https://img.chkaja.com/81f5ea5fdbe9374c.png" alt="81f5ea5fdbe9374c.png" title="81f5ea5fdbe9374c.png" />
<img src="https://img.chkaja.com/765f676e3c65fbba.png" alt="765f676e3c65fbba.png" title="765f676e3c65fbba.png" />

**Comment by caolvchong-top** [comment]
"cookie" : "auth_token=xxxxxxx;ct0=xxxxxxxxx;"
按照这个格式，除了最外面那一层的双引号，其他的双引号都去掉 

![68747470733a2f2f696d672e63686b616a612e636f6d2f383166356561356664626539333734632e706e67](https://github.com/caolvchong-top/twitter_download/assets/57820488/bbcda35d-dcf7-4aba-a945-be3a3c6a45ea)

**Comment by gewuagewua** [comment]
> "cookie"："auth_token=xxxxxxxx;ct0=xxxxxxxxxx;" 按照这个格式，除了最外面那一层的双引号，其他的双引号都去掉
> 
> ![68747470733a2f2f696d672e63686b616a612e636f6d2f383166356561356664626539333734632e706e67](https://private-user-images.githubusercontent.com/57820488/294397191-bbcda35d-dcf7-4aba-a945-be3a3c6a45ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzkwMDAsIm5iZiI6MTcwNDQzODcwMCwicGF0aCI6Ii81NzgyMDQ4OC8yOTQzOTcxOTEtYmJjZGEzNWQtZGNmNy00YWJhLWE5NDUtYmUzYTNjNmE0NWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA3MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YTRjYTA0MmE4ODNkMDQ5MmU5YTUyYjY0NDJjYzFjMzBmYzY5MmY3MTMzMjU3NjU5NjU1MmM5ZjMyOTc4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d8Q0jRzCCLDrRsyhI0mulHsTCocbXJF622undizM9j0)

引号去掉了，但还是报错
<img src="https://img.chkaja.com/681e4559dc22f2bf.png" alt="681e4559dc22f2bf.png" title="681e4559dc22f2bf.png" />

**Comment by caolvchong-top** [comment]
检查一下末尾的分号是否是 **英文半角** 符号 

![68747470733a2f2f696d672e63686b616a612e636f6d2f363831653435353964633232663262662e706e67](https://github.com/caolvchong-top/twitter_download/assets/57820488/0e30b7d5-3705-4f30-a228-bae00f822d69)

**Comment by gewuagewua** [comment]
> 检查一下末尾的分号是否是 **英文半角** 符号
> 
> ![68747470733a2f2f696d672e63686b616a612e636f6d2f363831653435353964633232663262662e706e67](https://private-user-images.githubusercontent.com/57820488/294423809-0e30b7d5-3705-4f30-a228-bae00f822d69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDAzOTcsIm5iZiI6MTcwNDQ0MDA5NywicGF0aCI6Ii81NzgyMDQ4OC8yOTQ0MjM4MDktMGUzMGI3ZDUtMzcwNS00ZjMwLWEyMjgtYmFlMDBmODIyZDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA3MzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjZjZDM1YzM4ZWVjODg1MWQzOWFlYmY2MDNiMGJlNDIzMDhjM2JkZmU3ZTU5MjA4MzA3ZTE5YTdiNDM1YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GF-sGde04861lPVkwDUBUyrPweCC_P3LuIzzQyUuuzI)

感谢大佬，这算成功了吗，已下载一直是0
<img src="https://img.chkaja.com/50d445ad2bc87542.png" alt="50d445ad2bc87542.png" title="50d445ad2bc87542.png" />

**Comment by gewuagewua** [comment]
哈哈，真不戳啊真不戳

**Comment by gewuagewua** [comment]
> 检查一下末尾的分号是否是 **英文半角** 符号
我下了600多应该到上限了吧。请问有暂停吗，我要是退出去第二天再会不会重复下载呢
<img src="https://img.chkaja.com/3cd236ee9384c8b7.png" alt="3cd236ee9384c8b7.png" title="3cd236ee9384c8b7.png" />

**Comment by gewuagewua** [comment]
>  检查一下末尾的分号是否是 **英文半角** 符号
> 
我下了600多应该到上限了吧。请问有暂停吗，我要是退出去第二天再会不会重复下载呢

> ![3cd236ee9384c8b7.png](https://camo.githubusercontent.com/47a371cdff1795fd9a4a4dea019aab94f65e61f0f9173f8b465df51359175f24/68747470733a2f2f696d672e63686b616a612e636f6d2f336364323336656539333834633862372e706e67)

**Comment by caolvchong-top** [comment]
这个是网不好，或者文件太大，超时时间内没能下载完成 

API上限会提示 **Rate limit exceeded** 然后自动退出程序 

第二次运行时会重复下载之前的内容，因为推特的分页设计，下一页的地址包含在前一页的response中

**Comment by gewuagewua** [comment]
但是我复制下载失败链接自己可以打开，这要怎么解决呢

**Comment by gewuagewua** [comment]
> 这个是网不好，或者文件太大，超时时间内没能下载完成
> 
> API上限会提示 **Rate limit exceeded** 然后自动退出程序
> 
> 第二次运行时会重复下载之前的内容，因为推特的分页设计，下一页的地址包含在前一页的response中

文件应该不是很大，大部分都是图片和短视频。我复制下载失败链接自己可以打开，这要怎么解决呢。

**Comment by caolvchong-top** [comment]
我没设置httpx的最大并发限制，过多请求把网络资源吃满导致超时，明天更新适配，这个问题会一并修复 

临时解决方案：不用管，放着让它下就行

**Comment by gewuagewua** [comment]
> 我没设置httpx的最大并发限制，过多请求把网络资源吃满导致超时，明天更新适配，这个问题会一并修复
> 
> 临时解决方案：不用管，放着让它下就行

感谢大佬，但现在有个新问题，我改了那个抓取时间之后报错，我想让他按时间顺序接着下来着
<img src="https://img.chkaja.com/005b7120a359ca3c.png" alt="005b7120a359ca3c.png" title="005b7120a359ca3c.png" />
<img src="https://img.chkaja.com/bcedb615a9c86845.png" alt="bcedb615a9c86845.png" title="bcedb615a9c86845.png" />
<img src="https://img.chkaja.com/3cd236ee9384c8b7.png" alt="3cd236ee9384c8b7.png" title="3cd236ee9384c8b7.png" />

**Comment by caolvchong-top** [comment]
是个bug，问题已经定位，明天一并修复 

临时解决方案： 
在文件main.py中的220行至221行之间加入以下内容： `_user_info.count += 1`

![image](https://github.com/caolvchong-top/twitter_download/assets/57820488/bbf88cf2-3a31-4cb8-8057-37aa95d9e6fa)
