### ISSUE TITLE
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

### ISSUE THREAD

**Issue by ErichKuhn** [caolvchong-top/twitter_download#23]
无法访问与值不关联的局部变量“response”，该怎么解决呢？
![6716402521a9cd6488d7d43ecf0a1be](https://github.com/caolvchong-top/twitter_download/assets/148173544/fffb380f-a3e8-42f4-9bf1-cdf1416d4b69)

**Comment by caolvchong-top** [comment]
可以贴一下你配置文件的非隐私部分吗

**Comment by ErichKuhn** [comment]
[image: image.png]是这个吗

Caolvchong ***@***.***> 于2024年1月6日周六 23:46写道：

**Comment by ErichKuhn** [comment]
![image](https://github.com/caolvchong-top/twitter_download/assets/148173544/3e5143bd-9263-4e01-94d4-978e811ed069)

**Comment by caolvchong-top** [comment]
运行一下以下代码，看一下输出： 
```
import httpx
import sys

print(sys.version)
print(httpx.__version__)
```

**Comment by ErichKuhn** [comment]
![image](https://github.com/caolvchong-top/twitter_download/assets/148173544/46f7efbf-ca8a-4f54-a562-4e3ff63e9c36)

**Comment by caolvchong-top** [comment]
试试0.23版本：`pip3 install httpx==0.23.0`

**Comment by ErichKuhn** [comment]
问题解决了，感谢大师！！你后面会考虑加入“统计点赞数、转发数、评论数”的功能吗？

**Comment by caolvchong-top** [comment]
> 问题解决了，感谢大师！！你后面会考虑加入“统计点赞数、转发数、评论数”的功能吗？

可以具体描述一下吗？统计哪部分数据，大概什么样的效果。

**Comment by ErichKuhn** [comment]
![image](https://github.com/caolvchong-top/twitter_download/assets/148173544/70edab2d-87bc-463e-86dc-3dfe6fe1027b)
就是把推文下面的这些数字也提取出来，最后写入CSV里面，像这样：
![image](https://github.com/caolvchong-top/twitter_download/assets/148173544/8e53a442-aa4d-49d9-80fe-432a59aee9e4)

**Comment by caolvchong-top** [comment]
浏览数没法添加，媒体标签页下不包含这个数据，其它三个可以，过两天更新

**Comment by ErichKuhn** [comment]
感激！期待你更多的杰作

**Comment by caolvchong-top** [comment]
已更新
