### ISSUE TITLE
您好，请问下这些api接口是从 哪里查询的？

### ISSUE THREAD

**Issue by uniquedist** [caolvchong-top/twitter_download#27]
我f12找的和代码里的不一样
![image](https://github.com/caolvchong-top/twitter_download/assets/66727650/b01322ff-ad6c-4f81-95f5-85efa9a309e0)
![image](https://github.com/caolvchong-top/twitter_download/assets/66727650/6282c095-99e9-4813-9bd2-49e18e1a8549)

**Comment by caolvchong-top** [comment]
我接口就f12找的 

不一样是因为推特更新过了，现在抓到的都和你图上的一样，代码里的是我以前抓的，目前还可以正常使用

**Comment by uniquedist** [comment]
确实，现在新的接口我试了下不行了，好的，谢谢
