### ISSUE TITLE
增量下载

### ISSUE THREAD

**Issue by Chankit8** [caolvchong-top/twitter_download#29]
大大，请问有可能基于最近下载的内容进行增量下载吗？日常经常会对同一账号多次下载，但不方便认为筛选分隔时间

**Comment by caolvchong-top** [comment]
可以再稍微详细一些吗，是继承前一次进度继续向后下载，还是下载新发布的内容

**Comment by Chankit8** [comment]
> 可以再稍微详细一些吗，是继承前一次进度继续向后下载，还是自动补全新发布的内容

大多数场景还是倾向于在上次下载的最后一个文件的时间点自动补全新发布的内容。

**Comment by caolvchong-top** [comment]
> 大多数场景还是倾向于在上次下载的最后一个文件的时间点自动补全新发布的内容。

明白了，近期更新

**Comment by caolvchong-top** [comment]
已更新，开启down_log选项后将时间范围拉大，如2030，运行后会自动补全新内容而跳过已有内容 

单独的自动补全有些难度，后续可能会更新
