### ISSUE TITLE
可以加入视频下载功能吗？

### ISSUE THREAD

**Issue by Sheng-Charles** [caolvchong-top/twitter_download#3]
有一个扩展很好用：Twitter Media Downloader ( version 0.1.5.4 )，它可以批量增量下载媒体，但我不想每天每个用户都点进去按下载XD 所以只能拜托你看看~https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig

**Comment by caolvchong-top** [comment]
已更新

**Comment by Sheng-Charles** [comment]
非常感谢！
