### ISSUE TITLE
获取信息失败

### ISSUE THREAD

**Issue by matcha6666** [caolvchong-top/twitter_download#30]
![屏幕截图 2024-02-12 181848](https://github.com/caolvchong-top/twitter_download/assets/143941342/35adbe28-96c7-432a-aa97-7a7354cd8249)

**Comment by caolvchong-top** [comment]
可以贴一下配置文件的非隐私部分吗

**Comment by matcha6666** [comment]
![屏幕截图 2024-02-12 22325](https://github.com/caolvchong-top/twitter_download/assets/143941342/cd3e6ed7-bac1-4c6d-88e0-e7c5afa2fcf8)
其余没改，只改了前三个

**Comment by caolvchong-top** [comment]
> ![屏幕截图 2024-02-12 22325](https://github.com/caolvchong-top/twitter_download/assets/143941342/cd3e6ed7-bac1-4c6d-88e0-e7c5afa2fcf8)
> 其余没改，只改了前三个

用户名不能带@符号

**Comment by matcha6666** [comment]
![屏幕截图 2024-02-12 224016](https://github.com/caolvchong-top/twitter_download/assets/143941342/12c343a6-7e44-47ed-9d59-cb4bff3d6773)
这种情况是关闭异步下载吗

**Comment by caolvchong-top** [comment]
> ![屏幕截图 2024-02-12 224016](https://github.com/caolvchong-top/twitter_download/assets/143941342/12c343a6-7e44-47ed-9d59-cb4bff3d6773)
> 这种情况是关闭异步下载吗

网络质量不佳的话可以考虑关闭

**Comment by matcha6666** [comment]
好的
