### ISSUE TITLE
补充增量判断代码后报错

### ISSUE THREAD

**Issue by Chankit8** [caolvchong-top/twitter_download#36]
补充增量判断代码后报错，麻烦作者大大帮忙看下是否与我本地自己修改的文件命名有关？
如下左侧为我自己修改的文件命名：
![Snipaste_2024-03-17_22-00-26](https://github.com/caolvchong-top/twitter_download/assets/35122233/925524c7-4f23-4350-9294-a43f77724be4)
以下为爬取信息：
![Snipaste_2024-03-17_22-00-10](https://github.com/caolvchong-top/twitter_download/assets/35122233/40f10ef9-6cb6-4c6b-96f3-c0b7ed0abccd)

**Comment by caolvchong-top** [comment]
是的，我没考虑到这个问题，已经修复了，更新即可

**Comment by Chankit8** [comment]
> 是的，我没考虑到这个问题，已经修复了，更新即可

已正常下载，感谢。
