### ISSUE TITLE
文件命名

### ISSUE THREAD

**Issue by justin-water** [caolvchong-top/twitter_download#4]
文件可以自定义命名吗

**Comment by caolvchong-top** [comment]
具体要什么样的呢？可以举个例子吗

**Comment by justin-water** [comment]
例如userID-time-vid/img1234

**Comment by caolvchong-top** [comment]
可以修改代码第199、153、158行实现，单独开个功能有点难，格式不统一
```
#第199行(文件夹命名)可以替换为:
_path = settings['save_path']+f'{_user_info.screen_name}-{time.time()}-自定义的名字'     #{time.time()} 时间戳,可以根据需要进行替换或修改

#第153行(视频文件命名)可以替换为:
_file_name = f'{_user_info.save_path + os.sep}自定义的名字-{_user_info.count + order}.mp4'   #{_user_info.count + order}是计数

#第158行(图片文件命名)可以替换为:
_file_name = f'{_user_info.save_path + os.sep}自定义的名字-{_user_info.count + order}.{img_format}'
```
<img width="719" alt="屏幕截图 2023-09-18 002421" src="https://github.com/caolvchong-top/twitter_download/assets/57820488/3460d62c-d866-47c1-9de5-9cbd3b5c5b21">

效果如下:

**Comment by justin-water** [comment]
3q

**Comment by TANCANJIE** [comment]
这里

> 可以修改代码第199、153、158行实现，单独开个功能有点难，格式不统一
> 
> ```
> #第199行(文件夹命名)可以替换为:
> _path = settings['save_path']+f'{_user_info.screen_name}-{time.time()}-自定义的名字'     #{time.time()} 时间戳,可以根据需要进行替换或修改
> 
> #第153行(视频文件命名)可以替换为:
> _file_name = f'{_user_info.save_path + os.sep}自定义的名字-{_user_info.count + order}.mp4'   #{_user_info.count + order}是计数
> 
> #第158行(图片文件命名)可以替换为:
> _file_name = f'{_user_info.save_path + os.sep}自定义的名字-{_user_info.count + order}.{img_format}'
> ```
> 
> 效果如下:
> 
> <img alt="屏幕截图 2023-09-18 002421" width="719" src="https://user-images.githubusercontent.com/57820488/268515225-3460d62c-d866-47c1-9de5-9cbd3b5c5b21.png">

这里应如何引用用户id参数呢，@后面的

**Comment by caolvchong-top** [comment]
> 这里应如何引用用户id参数呢，@后面的

`_user_info.screen_name`    **用户id**
`_user_info.name`                **用户昵称**

**Comment by caolvchong-top** [comment]
已统一格式
