### ISSUE TITLE
如何将推文作为文件名？

### ISSUE THREAD

**Issue by Sheng-Charles** [caolvchong-top/twitter_download#43]
RT

**Comment by caolvchong-top** [comment]
将281、284行分别改为
``` 
_file_name = f'{csv_info[7]}_{_user_info.count + order}.mp4'    #281
_file_name = f'{csv_info[7]}_{_user_info.count + order}.{img_format}'    #284
``` 
即可

![image](https://github.com/caolvchong-top/twitter_download/assets/57820488/034b189e-e508-47ab-b55f-ae03a957d202) 

**//不建议这么做，如果推文中含有特殊字符在windows中会直接报错 #39**
