### ISSUE TITLE
大佬有没有可能做个Scrapy版本？

### ISSUE THREAD

**Issue by Ricksanchez000** [caolvchong-top/twitter_download#44]
大佬有没有可能做个Scrapy版本？感觉Scrapy可拓展性和系统性比较强，无论是爬图片还是推文做学术

**Comment by caolvchong-top** [comment]
确实，原本这就是个小工具，现在已经是屎山了 

后面我会用Scrapy重构一下，加上一些其它功能，不过可能要过个一两月

**Comment by tiredcows** [comment]
大佬牛逼
