### ISSUE TITLE
大佬推特纯文字文本好像不能获取，需要更改什么地方呢

### ISSUE THREAD

**Issue by DKhacEC** [caolvchong-top/twitter_download#47]
大佬推特纯文字文本好像不能获取，需要更改什么地方呢

**Comment by caolvchong-top** [comment]
这个工具主要是获取媒体文件的，文本内容暂时还不支持，后面重构的时候会加上 #20

**Comment by DKhacEC** [comment]
大佬有联系方式吗

**Comment by DKhacEC** [comment]
可以交流交流吗

**Comment by caolvchong-top** [comment]
你可以直接发需求，或者我主页上有邮箱，发邮件也行

**Comment by DKhacEC** [comment]
源代码对于纯文本过滤了吗，输出的json文件中找不到纯文内容

**Comment by caolvchong-top** [comment]
首先要把设置中的 **[包含转推]** 选项打开，不打开默认调用的媒体API，不含文字内容。 

包含媒体文件的推文会有一个 **‘extended_entities’** 标签，在程序的179、183行会对这部分筛选，排除掉非文本内容

**Comment by DKhacEC** [comment]
筛选这块大佬能不能再讲解一下，应该怎么改呢

**Comment by caolvchong-top** [comment]
像179、180行就可以直接注掉 (也就是去掉筛选)，在原本的地方根据你需要的写下处理逻辑 （183、202那两个extended_entities判断也一样），然后注意最后的return，然后修改主函数部分 

//工程量可能有些大

**Comment by DKhacEC** [comment]
等大佬更新有点久，所以着急上手

**Comment by DKhacEC** [comment]
冒昧问下，大佬什么时候有时间更新

**Comment by caolvchong-top** [comment]
今明两天我会先更新个tag获取； 

你可以把具体需要的内容，最后存储的格式，还有其他的需求尽可能全面的描述一下，我可以试试先写个简易版 

不复杂的话可能后天吧

**Comment by caolvchong-top** [comment]
用什么方式存储呢？还是那个csv模板吗

**Comment by DKhacEC** [comment]
是的

**Comment by caolvchong-top** [comment]
行，我近期更新

**Comment by DKhacEC** [comment]
好的，感谢大佬

**Comment by caolvchong-top** [comment]
已更新

**Comment by DKhacEC** [comment]
ok，୧(๑•̀◡•́๑)૭

**Comment by DKhacEC** [comment]
line 160, in get_clean_save
    _time_stamp = int(raw_text['edit_control']['editable_until_msecs'])
KeyError: 'editable_until_msecs'
这个报错，大佬能解答一下吗，text_down.py的问题

**Comment by caolvchong-top** [comment]
> line 160, in get_clean_save _time_stamp = int(raw_text['edit_control']['editable_until_msecs']) KeyError: 'editable_until_msecs' 这个报错，大佬能解答一下吗，text_down.py的问题

应该是碰到特殊推文了，可以提供一下目标用户吗

**Comment by caolvchong-top** [comment]
已修复
