### ISSUE TITLE
一个运行问题·

### ISSUE THREAD

**Issue by dsqsde** [caolvchong-top/twitter_download#52]
![Snipaste_2024-05-23_09-31-58](https://github.com/caolvchong-top/twitter_download/assets/170588301/1e7ed805-f752-41ed-81cd-60e3ea49d28b)
请问我的运行环境是不是有问题？如何解决？

**Comment by caolvchong-top** [comment]
安装一下httpx 
`pip3 install httpx==0.23.0`
