### ISSUE TITLE
main.py-108行无法获取用户数据

### ISSUE THREAD

**Issue by brlve** [caolvchong-top/twitter_download#55]
cookie正确，但是无法获取数据。该url返回值为空，response=''

main.py的get_other_info函数无法获取用户信息，第108行
response = httpx.get(url, headers=_headers, proxies=proxies).text

**Comment by caolvchong-top** [comment]
可以看一下报错的截图吗？如果有修改代码的话请贴一下修改后的部分

**Comment by brlve** [comment]
![Uploading PixPin_2024-06-03_01-16-37.png…]()

**Comment by brlve** [comment]
发生异常: UnboundLocalError
local variable 'response' referenced before assignment
TimeoutError: _ssl.c:980: The handshake operation timed out

The above exception was the direct cause of the following exception:

httpcore.ConnectTimeout: _ssl.c:980: The handshake operation timed out

The above exception was the direct cause of the following exception:

  File "E:\test1\twitter_download-main\main.py", line 108, in get_other_info
    response = httpx.get(url, headers=_headers, proxies=proxies).text
httpx.ConnectTimeout: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

  File "E:\test1\twitter_download-main\main.py", line 117, in get_other_info
    print(response)
  File "E:\test1\twitter_download-main\main.py", line 336, in main
    if not get_other_info(_user_info):
  File "E:\test1\twitter_download-main\main.py", line 378, in <module>
    main(User_info(i))
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by caolvchong-top** [comment]
httpx版本的问题，具体可以参见这里  #23 

换成0.23.0就行了

**Comment by brlve** [comment]
还是一样的问题，httpx版本0.23.0一样response返回值为空

<img width="841" alt="PixPin_2024-06-03_01-30-54" src="https://github.com/caolvchong-top/twitter_download/assets/22557737/0bd3c1f0-a812-4c08-b2a6-6ea81c169126">

**Comment by caolvchong-top** [comment]
可以看一下配置文件吗

**Comment by brlve** [comment]
配置文件就是默认的，gitclone下来就添加了cookie

**Comment by brlve** [comment]
<img width="706" alt="PixPin_2024-06-03_01-38-39" src="https://github.com/caolvchong-top/twitter_download/assets/22557737/73a7ecc8-2c86-4e5f-a61c-e7066b1145f0">

**Comment by caolvchong-top** [comment]
> <img width="706" alt="PixPin_2024-06-03_01-38-39" src="https://github.com/caolvchong-top/twitter_download/assets/22557737/73a7ecc8-2c86-4e5f-a61c-e7066b1145f0">
> 

cookie的auth_token ，多打了一个a

**Comment by brlve** [comment]
。。。。不好意思。。。耽搁你了。谢谢谢谢
