### ISSUE TITLE
遇到的问题是有些用户的可以爬出来，有些爬不出来

### ISSUE THREAD

**Issue by lisongyan123** [caolvchong-top/twitter_download#56]

**Comment by caolvchong-top** [comment]
请提供一下有问题的用户名，以及配置文件的非隐私部分。

**Comment by hardwayp3nny** [comment]
elonmusk就爬不了

**Comment by hardwayp3nny** [comment]
{
    "save_path": "data",
    "save_path_info": "",
    "user_lst": "elonmask,OnchainDataNerd,layerggofficial",
    "user_lst_info": "填入要下载的用户名(@后面的字符),支持多用户下载,用户名字间逗号(英文逗号,不要有空格)隔开",
    "cookie": "",
    "cookie_info": "填入 cookie (auth_token与ct0字段) //重要:替换掉其中的x即可, 注意不要删掉分号",
    "emmmmmm": "以下选项三选一, 一般全false, 即 下载目标用户自己发的图片",
    "has_retweet": true,
    "has_retweet_info": "是否包含转推 (包含转推会消耗大量API调用次数)",
    "high_lights": false,
    "high_lights_info": "推特的 [Highlights]亮点 标签，与 [媒体][转推] 不共存，即仅下载亮点标签下的内容",
    "likes": false,
    "likes_info": "用户界面 [Likes] 标签页，即下载指定用户点过赞的推文，与 [媒体][转推][亮点] 不共存, 不支持时间范围限制默认全部下载(点赞时间无法获取), 不生成csv数据统计",
    "_emmmmmm_": "---------------",
    "time_range": "last_30_minutes",
    "time_range_info": "时间范围限制,格式如 1990-01-01:2030-01-01 ,不填默认无限制",
    "down_log": false,
    "down_log_info": "开启后将记录已下载的内容,避免重复下载浪费带宽; 注意:如需重新下载已下载内容,需要关闭此选项或删除目录下的 cache_data.log 文件",
    "autoSync": false,
    "autoSync_info": "开启后将基于本地已有的内容自动同步最新的部分, 本质上是自动调整时间范围的左半部分, 右半建议2030-01-01或更长, 每次运行时csv文件会被覆盖",
    "img_format": "png",
    "img_format_info": "下载图片/视频的质量(png为高质量,jpg为标准质量)",
    "has_video": true,
    "has_video_info": "是否下载推文中的视频",
    "log_output": false,
    "log_output_info": "是否需要下载过程日志输出",
    "async_down": true,
    "async_down_info": "异步下载,默认开启,网络不好时可以关闭,并发数量可在主函数11行修改",
    "proxy": "",
    "proxy_info": "手动配置代理,默认为空,非必要无需填写 格式: http://localhost:port ",
    "(๑´ڡ`๑)": "info 是注释，凑合着看吧"
}
