### ISSUE TITLE
麻烦请教一下，出现以下情况是怎么回事？

### ISSUE THREAD

**Issue by Lzcns** [caolvchong-top/twitter_download#57]
Traceback (most recent call last):
  File "E:\保存\twitter_download-main\main.py", line 57, in <module>
    settings = json.load(f)
               ^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 44 column 19 (char 1507)

刚开始是可以下载推的图片的，然后再运行就显示这些了。

而且一开始正常运行时，有几个推的图片总是提示下载失败重试，这个该如何处理呢？

**Comment by caolvchong-top** [comment]
可以提供一下配置文件的非隐私部分吗，目测是在第44行有格式错误

**Comment by Lzcns** [comment]
"save_path": "E:/保存/保存目录",
    "save_path_info": "就算是windows路径也请用 '/' ,而不是反斜杠(可以留空)",

    "user_lst": "shigenobanai",
    "user_lst_info": "填入要下载的用户名(@后面的字符),支持多用户下载,用户名字间逗号(英文逗号,不要有空格)隔开",

    "cookie": "auth_token=; ct0=;",
    "cookie_info": "填入 cookie (auth_token与ct0字段) //重要:替换掉其中的x即可, 注意不要删掉分号",


    "emmmmmm": "以下选项三选一, 一般全false, 即 下载目标用户自己发的图片",

    "has_retweet": false,
    "has_retweet_info": "是否包含转推 (包含转推会消耗大量API调用次数)",

    "high_lights": false,
    "high_lights_info": "推特的 [Highlights]亮点 标签，与 [媒体][转推] 不共存，即仅下载亮点标签下的内容",

    "likes": false,
    "likes_info": "用户界面 [Likes] 标签页，即下载指定用户点过赞的推文，与 [媒体][转推][亮点] 不共存, 不支持时间范围限制默认全部下载(点赞时间无法获取), 不生成csv数据统计",

    "_emmmmmm_": "---------------",
    

    "time_range": "1990-01-01:2024-06-23",
    "time_range_info": "时间范围限制,格式如 1990-01-01:2030-01-01 ,不填默认无限制",

    "down_log": false,
    "down_log_info": "开启后将记录已下载的内容,避免重复下载浪费带宽; 注意:如需重新下载已下载内容,需要关闭此选项或删除目录下的 cache_data.log 文件",

    "autoSync": false,
    "autoSync_info": "开启后将基于本地已有的内容自动同步最新的部分, 本质上是自动调整时间范围的左半部分, 右半建议2030-01-01或更长, 每次运行时csv文件会被覆盖",

    "img_format": "png",
    "img_format_info": "下载图片/视频的质量(png为高质量,jpg为标准质量)",

    "has_video": false,
    "has_video_info": "是否下载推文中的视频",

    "log_output": false,
    "log_output_info": "是否需要下载过程日志输出",

    "async_down": ture,
    "async_down_info": "异步下载,默认开启,网络不好时可以关闭,并发数量可在主函数11行修改",

**Comment by Lzcns** [comment]
cookie和代理没截取，其他的基本是这样子填写的

**Comment by caolvchong-top** [comment]
![image](https://github.com/caolvchong-top/twitter_download/assets/57820488/dc1366fa-ad2e-470a-b5d0-9403d208ba5c)
第四十四行这里，应该是true

**Comment by Lzcns** [comment]
啊，拼写错误出的问题，囧。。。刚重新运行了下，可以正常下载了，麻烦作者大大了。
