### ISSUE TITLE
How can I find the api?

### ISSUE THREAD

**Issue by Seauagain** [caolvchong-top/twitter_download#58]
Thank you for open sourcing the codes. I'm curious about how to find the corresponding API, such as https://api.twitter.com/graphql/xxx.

**Comment by caolvchong-top** [comment]
Thank you for your interest. The API were obtained by F12 developer tools on the Twitter web interface. You can do this by opening the Twitter website, pressing F12 to open the developer tools, switching to the "Network" tab, and then you will see the related requests in the list

like this : #27
