### ISSUE TITLE
可以根据爬取的用户名自动创建文件夹并写入吗

### ISSUE THREAD

**Issue by TANCANJIE** [caolvchong-top/twitter_download#6]
可以根据爬取的用户名自动创建文件夹并写入吗，就不需要每次都在save_path修改了，如果同时爬取多个用户名也不好处理

**Comment by caolvchong-top** [comment]
复制的cookie中有几个双引号，需要手动在引号前加上 反斜杠 转义

**Comment by TANCANJIE** [comment]
> 复制的cookie中有几个双引号，需要手动在引号前加上 反斜杠 转义

刚有看到重新处理可以了，谢谢。麻烦看下文件名自动创建的可以实现吗

**Comment by caolvchong-top** [comment]
文件夹是自动创建的，默认是用户昵称。save_path只是用来指定下载位置，可以留空

**Comment by TANCANJIE** [comment]
已解决，感谢。
