### ISSUE TITLE
大佬检查下目前还能用吗

### ISSUE THREAD

**Issue by pacemrc** [caolvchong-top/twitter_download#61]
今天突然运行报错了

**Comment by caolvchong-top** [comment]
几个主要功能经测试目前都没有问题，可以提供一下具体的错误信息吗

**Comment by pacemrc** [comment]
运行报错发生在main.py的get_other_info函数中
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/3a0d96c6-1140-4d31-81ea-0742a29f1c3e">
经测试response = httpx.get(url, headers=_headers, proxies=proxies).text方式无法获取到数据
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/0301a3bc-75d8-4d3a-8a5f-f6bb92b783c8">
而response = requests.get(url=url,headers=headers, proxies=proxies)方式可正常获取到数据
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/1aa31c6c-ef9f-41f7-90c6-8123d9306e42">
程序运行前后为更改配置和代码，麻烦大佬帮忙分析一下呗

**Comment by caolvchong-top** [comment]
可以运行以下代码，看一下输出：
```
import httpx
import sys

print(sys.version)
print(httpx.__version__)
```
另外可以贴一下配置文件的非隐私部分吗，我复现一下

**Comment by pacemrc** [comment]
我重新下载原项目代理，替换cookie和代理也是相同的报错。最近有重新安装过python版本，不知道是这个问题么。
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/1c512b0f-77ea-43b2-a0d3-76496ce2d70e">

**Comment by caolvchong-top** [comment]
httpx版本的问题，换成0.23即可
`pip3 install httpx==0.23.0`

**Comment by pacemrc** [comment]
可以了，谢谢大佬，建议在项目里加一个requirement.txt文件

**Comment by caolvchong-top** [comment]
其实我有在主页标明httpx版本问题的 

因为只要这一个包，所以没单开一个requirement
