### ISSUE TITLE
关于get_other_info中https返回403状态码问题

### ISSUE THREAD

**Issue by hinsxzx** [caolvchong-top/twitter_download#64]
目前使用两个旧账号和一个新账号的cookie跑您提供的代码，还设置了user_lst = ['jeleechandayo']，time_range = "2020-09-01:2024-09-01"，其他均不变。然而今天一直出现403的情况，已排除次数限制的问题，clash代理节点也更换数个。此情况昨天并没有遇到，昨天一切正常。大佬能分析一下吗？

**Comment by caolvchong-top** [comment]
程序刚测试了可以正常运行，感觉大概率是代理的问题，或者可以贴一下详细的错误信息(或截图)

**Comment by caolvchong-top** [comment]
这个意思是cookie错了(可能是`auth_token`部分)，你可以检查一下

**Comment by caolvchong-top** [comment]
请贴一下详细错误信息，以及该帐号访问网页、查看推文都正常吗
