### ISSUE TITLE
posst获取完全

### ISSUE THREAD

**Issue by CoffeeGeeker** [caolvchong-top/twitter_download#66]
你好，我想获取个人所有推文
总推数(含转推):1019

我通过媒体以及text_down 获取纯文字一共加起来不到800，并且没有highlights(没有开通）
请问还有什么没有获取吗

**Comment by caolvchong-top** [comment]
很难说，因为这是twitter自己统计的数据，我只是直接把它打印出来。删推、隐藏、封禁之类的可能都有影响，不清楚twitter的计算规则。

//理论上应该没有漏的

**Comment by CoffeeGeeker** [comment]
> 很难说，因为这是twitter自己统计的数据，我只是直接把它打印出来。删推、隐藏、封禁之类的可能都有影响，不清楚twitter的计算规则。
> 
> //理论上应该没有漏的

非常感谢，我发现了 转载的text没有被保存，请问目前有解决方法吗，text_down只是保存作者的纯文字的，但是转载的没有解决

**Comment by CoffeeGeeker** [comment]
> * 纯文本的转推没有适配，因为不太方便存记录，后面有机会就加个功能吧
> * 可以给一下具体的配置和问题信息吗，我看看能不能复现。

相关信息已经发送邮箱

**Comment by caolvchong-top** [comment]
`text_down` 已新增功能：`包含转推`
