### ISSUE TITLE
获取信息失败

### ISSUE THREAD

**Issue by lilyli1011** [caolvchong-top/twitter_download#67]
{
    "save_path": "C://Users/ltt/Desktop/tt",
    "save_path_info": "就算是windows路径也请用 '/' ,而不是反斜杠(可以留空)",
    "user_lst": "onBLUE_ed",
    "user_lst_info": "填入要下载的用户名(@后面的字符),支持多用户下载,用户名字间逗号(英文逗号,不要有空格)隔开",
    "cookie": "auth_token=; ct0=;",
    "cookie_info": "填入 cookie (auth_token与ct0字段) //重要:替换掉其中的x即可, 注意不要删掉分号",
    "emmmmmm": "以下选项三选一, 一般全false, 即 下载目标用户自己发的图片",
    "has_retweet": false,
    "has_retweet_info": "是否包含转推 (包含转推会消耗大量API调用次数)",
    "high_lights": false,
    "high_lights_info": "推特的 [Highlights]亮点 标签，与 [媒体][转推] 不共存，即仅下载亮点标签下的内容",
    "likes": false,
    "likes_info": "用户界面 [Likes] 标签页，即下载指定用户点过赞的推文，与 [媒体][转推][亮点] 不共存, 不支持时间范围限制默认全部下载(点赞时间无法获取), 不生成csv数据统计",
    "_emmmmmm_": "---------------",
    "time_range": "1990-01-01:2030-01-01",
    "time_range_info": "时间范围限制,格式如 1990-01-01:2030-01-01 ,不填默认无限制",
    "down_log": false,
    "down_log_info": "开启后将记录已下载的内容,避免重复下载浪费带宽; 注意:如需重新下载已下载内容,需要关闭此选项或删除目录下的 cache_data.log 文件",
    "autoSync": false,
    "autoSync_info": "开启后将基于本地已有的内容自动同步最新的部分, 本质上是自动调整时间范围的左半部分, 右半建议2030-01-01或更长, 每次运行时csv文件会被覆盖",
    "img_format": "png",
    "img_format_info": "下载图片/视频的质量(png为高质量,jpg为标准质量)",
    "has_video": false,
    "has_video_info": "是否下载推文中的视频",
    "log_output": false,
    "log_output_info": "是否需要下载过程日志输出",
    "async_down": true,
    "async_down_info": "异步下载,默认开启,网络不好时可以关闭,并发数量可在主函数11行修改",
    "proxy": "",
    "proxy_info": "手动配置代理,默认为空,非必要无需填写 格式: http://localhost:port ",
    "(๑´ڡ`๑)": "info 是注释，凑合着看吧"
}

只把cookie截掉了

**Comment by geek2024811** [comment]
我的也是获取信息失败

**Comment by caolvchong-top** [comment]
> 我的也是获取信息失败
> 

可以贴一下报错信息的截图吗？程序经测试是正常的

**Comment by geek2024811** [comment]
![image](https://github.com/user-attachments/assets/aaaa5a18-e55d-4179-a724-968f06339235)

**Comment by lilyli1011** [comment]
<img width="551" alt="Snipaste_2024-10-01_07-57-06" src="https://github.com/user-attachments/assets/b025b2fa-0921-4e26-a92f-a455b1d4ca4f">

**Comment by ranaoyang** [comment]
检查一下是否完成了这一步
`pip3 install httpx==0.23.0`

**Comment by lilyli1011** [comment]
我执行了 pip install httpx，会跟版本号有关吗

**Comment by ranaoyang** [comment]
readme 不是说了吗
`#非0.23版本可能会出现不知名问题`

**Comment by lilyli1011** [comment]
哦哦哦没有注意，已经可以使用了，谢谢你

**Comment by caolvchong-top** [comment]
> ![image](https://private-user-images.githubusercontent.com/173036424/372272386-aaaa5a18-e55d-4179-a724-968f06339235.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NTI2NTAsIm5iZiI6MTcyNzc1MjM1MCwicGF0aCI6Ii8xNzMwMzY0MjQvMzcyMjcyMzg2LWFhYWE1YTE4LWU1NWQtNDE3OS1hNzI0LTk2OGYwNjMzOTIzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwMzEyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTg1NDc3OTk2YTMzZTQyMTg2Y2U4N2VkY2E4YThjZTMwMWNlNWVhZWUxYzc3OWYyNGQ3NTFjYWNiOTdiMWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8dPE25R7ucXYk-nqeE83IcJ1d1QkYDz6sAer705dd9Y)

https://github.com/caolvchong-top/twitter_download/issues/67#issuecomment-2384586513 可以检查一下httpx版本的问题
