### ISSUE TITLE
python3.13版本下安装了httpx0.23.0，运行main.py报错

### ISSUE THREAD

**Issue by karasu10** [caolvchong-top/twitter_download#71]
报错行如下
PS F:\twitter_download-main> pip3 install httpx==0.23.0
>> 
Collecting httpx==0.23.0
  Downloading httpx-0.23.0-py3-none-any.whl.metadata (52 kB)
Collecting certifi (from httpx==0.23.0)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting sniffio (from httpx==0.23.0)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting rfc3986<2,>=1.3 (from rfc3986[idna2008]<2,>=1.3->httpx==0.23.0)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting httpcore<0.16.0,>=0.15.0 (from httpx==0.23.0)
  Using cached httpcore-0.15.0-py3-none-any.whl.metadata (15 kB)
Collecting h11<0.13,>=0.11 (from httpcore<0.16.0,>=0.15.0->httpx==0.23.0)
  Using cached h11-0.12.0-py3-none-any.whl.metadata (8.1 kB)
Collecting anyio==3.* (from httpcore<0.16.0,>=0.15.0->httpx==0.23.0)
  Using cached anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting idna>=2.8 (from anyio==3.*->httpcore<0.16.0,>=0.15.0->httpx==0.23.0)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Downloading httpx-0.23.0-py3-none-any.whl (84 kB)
Using cached httpcore-0.15.0-py3-none-any.whl (68 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached anyio-3.7.1-py3-none-any.whl (80 kB)
Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached h11-0.12.0-py3-none-any.whl (54 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Installing collected packages: rfc3986, sniffio, idna, h11, certifi, anyio, httpcore, httpx
Successfully installed anyio-3.7.1 certifi-2024.8.30 h11-0.12.0 httpcore-0.15.0 httpx-0.23.0 idna-3.10 rfc3986-1.5.0 sniffio-1.3.1
PS F:\twitter_download-main> & D:/py313/python.exe f:/twitter_download-main/main.py
Traceback (most recent call last):
  File "f:\twitter_download-main\main.py", line 4, in <module>
    import httpx
  File "D:\py313\Lib\site-packages\httpx\__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "D:\py313\Lib\site-packages\httpx\_api.py", line 4, in <module>
    from ._client import Client
  File "D:\py313\Lib\site-packages\httpx\_client.py", line 9, in <module>
    from ._auth import Auth, BasicAuth, FunctionAuth
  File "D:\py313\Lib\site-packages\httpx\_auth.py", line 10, in <module>
    from ._models import Request, Response
  File "D:\py313\Lib\site-packages\httpx\_models.py", line 1, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'

**Comment by caolvchong-top** [comment]
3.11后的python似乎已经不支持0.23的httpx了，

目前看还是建议换成3.10版本，可以开个虚拟环境
