### ISSUE TITLE
大佬您好 我想问一下为何抓取到2021年的推文后就结束了

### ISSUE THREAD

**Issue by hitomi0413** [caolvchong-top/twitter_download#72]
也没有任何报错 就是正常的结束了 但该账号是2019年创建的 用X的高级搜索也能搜到之前的图文

**Comment by caolvchong-top** [comment]
大概率是触底了，可以参考这个 #63

**Comment by hitomi0413** [comment]
我使用tag_down的高级搜索后 还是下载不完那个时间段里的图片也是因为触底吗 该如何解决呢

**Comment by hitomi0413** [comment]
> 也没有任何报错 就是正常的结束了 但该账号是2019年创建的 用X的高级搜索也能搜到之前的图文

解决了 将media_latest = True就可以正常下载了 感谢作者
