### ISSUE TITLE
但是每次运行时  有新的内容了 旧的csv并还没有被覆盖

### ISSUE THREAD

**Issue by duya673** [caolvchong-top/twitter_download#73]
大佬 这个功能开启后并没有覆盖原有的csv 而是又创建了一个只有新内容的csv
![image](https://github.com/user-attachments/assets/dd0edbf1-d6b6-4cc5-a2f3-ca8e3a664686)
![image](https://github.com/user-attachments/assets/61c5ed75-d50d-4876-898c-f2ce091b65fc)

**Comment by caolvchong-top** [comment]
之前改了记录函数的命名规则，忘记修改相关描述了，已更正。 

记录函数只负责记录本次运行的内容，所以每次运行都会生成csv，配合autosync即每个csv中只包含新下载的内容

**Comment by duya673** [comment]
你太速度了吧 大神！！！ 表白！  客户因为这个折磨我两周了
