### ISSUE TITLE
tagdown运行中出现的问题

### ISSUE THREAD

**Issue by t0moon** [caolvchong-top/twitter_download#75]
![410f47c5a9b927884247e0cbb198c80](https://github.com/user-attachments/assets/495a7d24-509f-4bf3-9395-571bf3e7e63d)
大佬你好~请问出现这种情况是为什么鸭

**Comment by t0moon** [comment]
能运行的时候，我选择的是两个关键词的交集，时间限制为一天；现在用的是一个关键词，扩大了数据的总量，时间限制没有改

**Comment by t0moon** [comment]
谢谢大佬，但是出现新的报错。大佬好好休息，我不急的！
![image](https://github.com/user-attachments/assets/c883f183-9a04-4707-a4d6-da8821cdd1c3)

**Comment by caolvchong-top** [comment]
这个看起来是网络问题，可以检查一下你的代理工具 

或者运行这段程序来测试一下：https://github.com/caolvchong-top/twitter_download/issues/16#issuecomment-1817870078

**Comment by t0moon** [comment]
![image](https://github.com/user-attachments/assets/f526cbb8-ffe1-4a73-aa6d-eb3a1e19f50a)
![image](https://github.com/user-attachments/assets/970e3732-c1ea-4485-83dd-2524ba535405)
![image](https://github.com/user-attachments/assets/a37a5522-8042-4d3e-907f-c246f1c9ab8e)
你好，在测试过网络之后，代码运行后会出现这两种报错方式

**Comment by t0moon** [comment]
目前已经在环境变量和终端中配置全局代理^^

**Comment by caolvchong-top** [comment]
可以检查一下httpx版本的问题 #https://github.com/caolvchong-top/twitter_download/issues/67#issuecomment-2384586513

**Comment by t0moon** [comment]
![image](https://github.com/user-attachments/assets/6d8b4f5b-d06e-437d-9028-e1d4c681dfb9)
大佬，httpx已经是0.23

**Comment by caolvchong-top** [comment]
python用的什么版本呢

**Comment by t0moon** [comment]
python是3.10

**Comment by caolvchong-top** [comment]
可否将代码发到我的邮箱(无需cookie)，我目前复现不了这个问题，需要实际测试一下 
caolvchong007@gmail.com

**Comment by t0moon** [comment]
大佬 有爬取特定推文评论区的代码吗

**Comment by Dai0-2** [comment]
我也出现了KeyError: 'data'这个问题，请问后面怎么解决的

**Comment by t0moon** [comment]
> 我也出现了KeyError: 'data'这个问题，请问后面怎么解决的

我记得好像是换节点+等一会就好

**Comment by caolvchong-top** [comment]
> 我也出现了KeyError: 'data'这个问题，请问后面怎么解决的

KeyError: 'data' 很大可能是cookie问题，请检查cookie是否正确填写，有无过期；也有可能网络问题

**Comment by Dai0-2** [comment]
是换什么节点，我是在服务器上跑的

**Comment by Dai0-2** [comment]
cookie是我自己账号的，但是好像不能使用不知道为啥

**Comment by caolvchong-top** [comment]
> cookie是我自己账号的，但是好像不能使用不知道为啥

如果账号可以正常使用的话，请检查一下填写格式，可能会漏个数字字母之类的
``` 
"cookie": "auth_token=xxxxxxxxxxx; ct0=xxxxxxxxxxx;",
"cookie_info": "填入 cookie (auth_token与ct0字段) //重要:替换掉其中的x即可, 注意不要删掉分号",
```

**Comment by Dai0-2** [comment]
填写应该是没错的，刚才第一次爬了一个标签的图片，我想换一个标签就报错了

**Comment by caolvchong-top** [comment]
可否提供一下前后两次的标签，我测试一下

**Comment by Dai0-2** [comment]
# tag = '#台北101大厦'
tag = '总统府'
# tag = '#鸡南山'
这是我需要的三次标签

**Comment by caolvchong-top** [comment]
> tag = '#台北101大厦'
> tag = '总统府'
> 
> tag = '#鸡南山'
> 这是我需要的三次标签

三个经测试都可以正常下载。报错只报了`KeyError: 'data'`吗？
其余的配置项都保持的默认吗，另外可以检查一下账号目前能否正常访问推文

**Comment by Dai0-2** [comment]
作者你好图片能下载了，但是在爬取tag = '#台北101大厦'的文本时候将参数改为text_down = True
出现报错：无过程输出...(๑´ڡ`๑)
Traceback (most recent call last):
  File "/home/data/crawl/twitter_download/tag_down.py", line 334, in <module>
    tag_down()
  File "/home/data/crawl/twitter_download/tag_down.py", line 166, in __init__
    self.search_save_text(url)
  File "/home/data/crawl/twitter_download/tag_down.py", line 297, in search_save_text
    raw_data_lst = raw_data[0]['entries']
KeyError: 'entries'

且输出的csv文件只有如下内容
Run Time : 2025-01-08 05-32-06
Tweet Date,Display Name,User Name,Tweet URL,Tweet Content,Favorite Count,Retweet Count,Reply Count
2022-08-04 02:31,Billy中原佛手,@zhongyuanfoshou,https://twitter.com/@zhongyuanfoshou/status/1555025998772461569,"Watch DC Concept | #DC概念 live on GETTR.
EP69. #台北101大厦 #Taipei101
#李祖原 大师代表作之一，建筑文化意象和信仰意义‼️
#佩洛西访台 #台湾 #莲花台 #玉琮 #郑州裕达 #中原佛手 #如意 #Taiwan

",2,1,0
2022-03-22 09:37,时尚精品,@zhouyanjin2,https://twitter.com/@zhouyanjin2/status/1506210974147129344,"今日推荐。香水，手袋。
#ootd
#台北101大厦 ",0,0,0
2016-09-06 13:10,Teng Loo,@teng_loo,https://twitter.com/@teng_loo/status/773153895572840448,"每一件事都要用多方面的角度来看它❤️
#台北101大厦
#BMRTIncentiveTrip ",0,0,0

**Comment by caolvchong-top** [comment]
> 作者你好图片能下载了，但是在爬取tag = '#台北101大厦'的文本时候将参数改为text_down = True 出现报错 

因为已经触底了，只有三条内容 
![image](https://github.com/user-attachments/assets/75005de7-38ab-4dbb-a2b6-6975ec5f88ba)

**Comment by Dai0-2** [comment]
这种情况怎么办呢

**Comment by caolvchong-top** [comment]
> 这种情况怎么办呢

我马上会推一个小更新，目前正在测试

**Comment by Dai0-2** [comment]
好的

**Comment by Dai0-2** [comment]
可是为什么爬文本时候已经触底，但是爬图片的时候，却能爬100多张图片

**Comment by Dai0-2** [comment]
作者你好，我把tag中的#删掉了，这样他就是直接检索的信息，输出的文本就还算比较丰富

**Comment by Dai0-2** [comment]
嗯嗯，tag = "\"鸡南山\""似乎可以用这样精确搜索的方式搜索
