### ISSUE TITLE
想问下，如果我要做到实时不停的根据关键字爬取收集数据，能够做到这个吗

### ISSUE THREAD

**Issue by a805034104** [caolvchong-top/twitter_download#76]

**Comment by caolvchong-top** [comment]
应该可以，目标是文本还是媒体数据？ 
每次获取都单开一个csv记录，还是合到一起？ 
重复的数据是否要滤除？ 
是否还有其它需求

**Comment by YvQue** [comment]
linux写个脚本对本程序进行循环调用会不会是一种简单快捷的实现方式？

**Comment by ahuangg** [comment]
如果在循环中调用，不会触发速率限制吗

**Comment by a805034104** [comment]
> 应该可以，目标是文本还是媒体数据？ 每次获取都单开一个csv记录，还是合到一起？ 重复的数据是否要滤除？ 是否还有其它需求

文本，重复的数据要过滤，每次都单开吧。

**Comment by caolvchong-top** [comment]
> 文本，重复的数据要过滤，每次都单开吧。 

目前来看还是倾向于外部写个脚本定时调用，
后续可能会加上自动同步或是后台运行之类的功能，但api次数限制是个问题
