### ISSUE TITLE
文件命名可否按照一定格式

### ISSUE THREAD

**Issue by TANCANJIE** [caolvchong-top/twitter_download#8]
参考：
img文件命名格式姓名：twitterId-发布时间-img1.jpg
viedeo文件命名格式形如：twitterId-发布时间-vid.mp4

**Comment by caolvchong-top** [comment]
关于这个可以参见 #4 
[ 发布时间 ] 当前不支持，今晚或明天会提交 [ 限定时间范围 ] 的更新(#7 )，届时可通过 `_user_info.msecs` 调用

**Comment by caolvchong-top** [comment]
已更新
