### ISSUE TITLE
咨询：所下载推文的文案内容导出

### ISSUE THREAD

**Issue by Chankit8** [caolvchong-top/twitter_download#9]
会出现一个场景是除了需要的媒体资源外还会用到推文的文本内容，
以前有款[twitter media downloader](https://github.com/fanxy121/twMediaDownloader)扩展程序打包下载时会同步生成一个csv文件，里面主要包含推主信息，以及如下字段：
Tweet date、Action date、Display name、Username、Tweet URL、Media type	、Media URL、Saved filename、Remarks、Tweet content、Replies、Retweets、Likes
以上字段中推主信息和推文内容tweet content比较重要，想了解下大佬能否实现呢？是否有这方面考虑

**Comment by caolvchong-top** [comment]
应该可以，下周更新

**Comment by Chankit8** [comment]
> 应该可以，下周更新

以下是对应csv文件内容参考，感谢。
<img width="1080" alt="Snipaste_2023-10-06_19-52-28" src="https://github.com/caolvchong-top/twitter_download/assets/35122233/aee4e889-afd1-47eb-8f81-b49630d768c1">

**Comment by caolvchong-top** [comment]
已更新

**Comment by Chankit8** [comment]
> 已更新

哈喽，想问下这个csv文件可以放到对应用户的文件夹内么

**Comment by caolvchong-top** [comment]
> 
> 哈喽，想问下这个csv文件可以放到对应用户的文件夹内么

坏了，忘记处理文件夹了（'へ'）

**Comment by caolvchong-top** [comment]
已修复

**Comment by Chankit8** [comment]
> 已修复

辛苦大佬，可以了，感谢。
